Texture Updates/Revisions
Rearth/Oritech pull request #194
Opened 2024-12-07 05:44 UTC by BLOKBUSTR

I've revised most of the component items, such as ingots and dusts, and I've slightly tweaked the colors of the reinforced plating blocks. These changes mostly include cleaned up color palettes, item shapes and gradients to keep better consistency.

Changed items:
*Adamant Dust & Ingot - Biosteel Dust & Ingot - Carbon Fibre Strands - Coal Dust - Duratium Dust & Ingot - Electrum Dust & Ingot - Energite Dust & Ingot - Flux Gate - Fluxite - Iron Clump, Small Clump, Dust & Small Dust - Steel Dust & Ingot*

Items revised since our last PR:
*Copper Clump - Gold Clump & Small Clump - Nickel Ingot, Nugget, Dust, Gem & Small Dust*

Changed blocks:
*Iron Plating Block - Nickel Plating Block - Nickel Resource Node*

Blocks revised since our last PR:
*Nickel Ore & Deepslate Nickel Ore*

I'd like to make another follow-up PR later once I work on more textures. If there's anything you want to be changed or reverted, or if something looks out of place, let me know.

2024-12-11 22:33 UTC, Rearth requested changes
Hi, huge thanks for all the changes. Most of them look great. Having the clumps, dusts, etc in a similar shape and form is a huge plus. I really appreciate the work that went into this. I added comments to a few changes, but it's nothing major

2024-12-11 22:33 UTC, Rearth commented on common/src/main/resources/assets/oritech/textures/item/adamant_ingot.png
I do prefer the "shinyness" of the old texture here. Can we keep that somehow? Or just keep the old texture here, I think it looks fine as is

2024-12-11 22:33 UTC, Rearth commented on common/src/main/resources/assets/oritech/textures/item/electrum_ingot.png
Same here as with the adamant. The gradient makes it much easier to tell the ingots apart I think

2024-12-11 22:33 UTC, Rearth commented on common/src/main/resources/assets/oritech/textures/block/iron_plating_block.png
I actually really like the "popping" colors of the current platings and would prefer to keep them. Can you leave them out of the PR / revert those parts?

2024-12-11 22:44 UTC, BLOKBUSTR commented
I'll get to work on those changes when I return home later. I've also been thinking that I could add a little extra variation to the dust textures, as most of them are pretty much recolored gunpowder.

2024-12-12 21:15 UTC, BLOKBUSTR commented on common/src/main/resources/assets/oritech/textures/block/iron_plating_block.png
I've replaced my textures with the originals,, since I don't know if there's an option to exclude files from PRs. Hopefully this should work out.

2024-12-14 19:55 UTC, The4codeblocks commented
> as most of them are pretty much recolored gunpowder.

I don't think that's an issue if all vanilla dusts can be considered recolored gunpowder

2024-12-16 20:41 UTC, Rearth commented
They are looking great now, huge thanks again. Will merge it to include them in the next release

2024-12-16 20:41 UTC, merged